HCK-CI/AutoHCK

bin/auto_hck
lib/client.rb
lib/tests.rb

This reverts commits:
e62ad068a801d5a768812a5b4c627849aa96c670
241a3c367f3e4622438a723711065624c1a24f3e
Do not merge yet, not tested yet.

Reverting multiple clients tests optimization

---

lib/cli.rb

Adding missing -D cli argument for debug

---

lib/tools.rb

Fixing a variable name typo

---

lib/tools.rb

Handling invalid driver installation

---

bin/auto_hck
lib/tools.rb
lib/virthck.rb

Fixing rubocop offenses

---

README.md
config.json
lib/dropbox.rb
lib/github.rb

Removing hardcoded token and replacing with environment variables

---

README.md

Updating workspace results files documentation

---

devices.json

Updating NetKVM blacklist

---

bin/auto_hck
lib/client.rb
lib/monitor.rb
lib/studio.rb
lib/virthck.rb

This is the same as pull/29 but with the requested changes and rubocop fixes.

Fix TERM signal handling and graceful shutdown

---

bin/auto_hck

Fix concurrent testing

---

lib/dropbox.rb

Fixing rescue without specifying explicit exception class

---

lib/virthck.rb

Enabling VirtHCK dump

---

platforms.json

Fix 1809 platforms images names

---

devices.json

Blacklisting "Static Tools Logo Test" for NetKVM and vioscsi

---

lib/client.rb

To prevent hangs that happen due to client being stuck on restarting, a
timeout was configured to wrap the dunctionality of the method that
waits for the client up, (default duration was set to be 30 minutes).

Wrapping method for waiting client up in a timeout

---

Gemfile
bin/auto_hck
lib/cli.rb
lib/client.rb
lib/diff_checker.rb
lib/dropbox.rb
lib/github.rb
lib/id_gen.rb
lib/monitor.rb
lib/multi_logger.rb
lib/playlist.rb
lib/project.rb
lib/result_uploader.rb
lib/studio.rb
lib/targets.rb
lib/tests.rb
lib/tools.rb
lib/virthck.rb

1. Update to Client's name and added tag instance variable
2. Updated Client recognize and initialize waits implementations
3. Tools class updates to machine action methods
4. Optimizing VirtHCK setup and configure process
5. Client run to be more informative
6. Robust abort process for Studio and Client
7. Studio and Client check alive update
8. Minor exception backtrace logging bug fix
9. Fixing new rubocop version 0.69 offenses

Major updates

---

bin/auto_hck
lib/client.rb
lib/targets.rb
lib/tools.rb

Robustness of the targeting process
Increased Tools action retires on failure to 5
Better logging of a Tools action failure

Minor follow up updates to my last major PR

---

lib/virthck.rb

Signed-off-by: Basil Salman <Basil@daynix.com>

Id allocation retry in case generator is busy

---

platforms.json

Signed-off-by: Lior Haim <lior@dotcore.co.il>

Updating platorm list with new HLK1903

---

lib/cli.rb
lib/version.rb

Signed-off-by: Ali Abu-Foul <ali@daynix.com>

Adding versioning for AutoHCK

---

devices.json
triggers.yml.example

Signed-off-by: Ali Abu-Foul <ali@daynix.com>

Adding vsock driver

---

bin/auto_hck
config.json
lib/cli.rb
lib/client.rb
lib/engine.rb
lib/exceptions.rb
lib/monitor.rb
lib/project.rb
lib/studio.rb
lib/virthck.rb

Signed-off-by: Basil Salman <basil@daynix.com>

Engine separation from autoHCK

---

lib/engine.rb
lib/virthck.rb

Signed-off-by: Basil Salman <Basil@daynix.com>

Moving the responsibility to release id from virhck to engine

---

devices.json
engines/virthck.json
engines/virthck.rb

Signed-off-by: Basil Salman <basil@daynix.com>

Added virtiofs support

---

lib/setupmanagers/hckclient.rb

Signed-off-by: Basil Salman <Basil@daynix.com>

Fixed a typo

---

lib/setupmanagers/hckstudio.rb

Signed-off-by: Basil Salman <basil@daynix.com>

Fix: Cleanup While tools is nil

---

lib/exceptions.rb
lib/project.rb

Signed-off-by: Basil Salman <basil@daynix.com>

Don't run test if commit hash invalid

---

bin/auto_hck
lib/auxiliary/diff_checker.rb
lib/auxiliary/github.rb
lib/auxiliary/host_helper.rb
lib/auxiliary/id_gen.rb
lib/auxiliary/json_helper.rb
lib/auxiliary/multi_logger.rb
lib/cli.rb
lib/engines/engine.rb
lib/engines/exceptions.rb
lib/engines/hcktest/hcktest.rb
lib/engines/hcktest/playlist.rb
lib/engines/hcktest/targets.rb
lib/engines/hcktest/tests.rb
lib/engines/hcktest/tools.rb
lib/exceptions.rb
lib/project.rb
lib/resultuploaders/dropbox.rb
lib/resultuploaders/result_uploader.rb
lib/setupmanagers/exceptions.rb
lib/setupmanagers/hckclient.rb
lib/setupmanagers/hckstudio.rb
lib/setupmanagers/machine.rb
lib/setupmanagers/monitor.rb
lib/setupmanagers/physhck/physhck.rb
lib/setupmanagers/setupmanager.rb
lib/setupmanagers/virthck/virthck.rb
lib/version.rb

Please look in commit messages for more details.
Tested on Groan server
@Basils Should we test these changes in other servers?

Move all code into AutoHCK module (namespace)

---

bin/auto_hck
lib/engines/engine.rb
lib/engines/hcktest/hcktest.rb
lib/engines/hcktest/playlist.rb
lib/engines/hcktest/targets.rb
lib/engines/hcktest/tools.rb
lib/project.rb
lib/setupmanagers/hckclient.rb
lib/setupmanagers/machine.rb
lib/setupmanagers/physhck/physhck.rb
lib/setupmanagers/setupmanager.rb
lib/setupmanagers/virthck/virthck.rb
lib/version.rb

Please see the commits message for more details

AutoHCK new features

---

ImageInstallation.md
README.md

[RFC] Update documentation according to the latest changes

---

.github/workflows/rubocop.yml
Gemfile
lib/auxiliary/downloader.rb
lib/auxiliary/host_helper.rb
lib/engines/hckinstall/hckinstall.rb
lib/engines/hckinstall/kit.json
lib/engines/hckinstall/setup_scripts_helper.rb
lib/setupmanagers/hckstudio.rb

The next limitation fixed
- studio and client VMs will be installed from the one Windows ISO - **client platform will be parsed from filename**
- the corresponding version of HCK/HLK should be downloaded manually - **automatic download will be implemented**

Image creation improvements

---

lib/resultuploaders/dropbox.rb

dropbox: Retry API call in case of error

---

lib/version.rb

New feature added, so bump the minor version

Bump auto_hck version (0.7.0)

---

lib/engines/hckinstall/kit.json
lib/engines/hckinstall/studio_platform.json
lib/engines/hcktest/platforms/Win2022x64.json

Add Win2022x64 platform

---

drivers.json
lib/setupmanagers/qemuhck/devices/vmcoreinfo.json

drivers: Add QEMU FwCfg Device

---

.github/workflows/rubocop.yml
Gemfile
Gemfile.lock

Update RuboCop CI config

---

bin/auto_hck
lib/engines/hcktest/tools.rb
lib/setupmanagers/hckclient.rb
lib/setupmanagers/qemuhck/qemu_machine.rb
lib/trap.rb

See the respective commit messages for details.
Commit 2399c942520548a85ec84e637106c4a8abc99be0 supersedes #147.

Trap, interrupt, initialization improvements

---

lib/engines/hcktest/tests.rb

tests: Do not sleep after applying filters

---

lib/project.rb

Using `StringIO` instead of a file saves the code to unlink the file and also avoids that a file persists with an abnormal exit.

project: Use StringIO for multilog

---

lib/engines/engine.rb
lib/engines/hckinstall/hckinstall.rb
lib/engines/hcktest/hcktest.rb
lib/project.rb
lib/setupmanagers/hckclient.rb
lib/setupmanagers/hckstudio.rb
lib/setupmanagers/physhck/physhck.rb
lib/setupmanagers/qemuhck/network_manager.rb
lib/setupmanagers/qemuhck/qemu_machine.rb
lib/setupmanagers/qemuhck/qemuhck.rb
lib/setupmanagers/setupmanager.rb

engines: Abort each run

---

lib/resultuploaders/dropbox.rb
lib/setupmanagers/qemuhck/network_manager.rb
lib/setupmanagers/qemuhck/qemu_machine.rb

Use File.read/write as a safer API

---

lib/auxiliary/github.rb
lib/config/sentry.rb
lib/resultuploaders/dropbox.rb
lib/setupmanagers/qemuhck/qemuhck.rb

Use ENV.fetch to avoid bugs with unset variables

---

drivers.json
lib/engines/hcktest/hcktest.rb
lib/engines/hcktest/playlist.rb
lib/engines/hcktest/tests.rb
svvp.json

Replace blacklist with ignore list

---

lib/engines/hcktest/tools.rb

tools: Avoid using numbered parameters

---

lib/auxiliary/id_gen.rb

Use heredoc for SQL

---

lib/setupmanagers/hckstudio.rb

Remove extra nil check

---

bin/ns_unshared
lib/auxiliary/cmd_run.rb
lib/setupmanagers/qemuhck/network_manager.rb
lib/setupmanagers/qemuhck/qemu_machine.rb
lib/setupmanagers/qemuhck/slirp.rb

Replate numbered parameters in multi-line blocks

---

lib/engines/hcktest/tests.rb
lib/setupmanagers/qemuhck/qemu_machine.rb

Fix RuboCop AmbiguousOperatorPrecedence offense

---

lib/version.rb

Merge after https://github.com/HCK-CI/AutoHCK/pull/157

Bump AutoHCK version (0.10.3)

---

lib/cli.rb
lib/project.rb

This allows to user triggers file from a repository instead of file from CI installer.

CLI: Add option to specify the triggers files

---

Gemfile
Gemfile.lock
drivers.schema.json
spec/json_validation_spec.rb

This is the initial commit of JSON schemas and validation. For now, allow to have JSONs without schema.
I will send the next PRs with other schemas and changes in the source (if necessary)

Add JSON validation tests

---

lib/engines/hckinstall/kit.json
lib/engines/hcktest/platforms/Win2025x64_host_uefi_q35.json

Disable_SNV is required for all Insider Preview release. Will remove after public release.

Add Win2025 platform

---

lib/setupmanagers/qemuhck/network_manager.json

Need to review this part after multi-queue will be added.

qemuhck: Set txqueuelen for all tap devices and bridge

---

.rubocop.yml
bin/ns
bin/ns_unshared
bin/unix_spawn
lib/auxiliary/extra_software/manager.rb
lib/auxiliary/host_helper.rb
lib/auxiliary/pgroup.rb
lib/auxiliary/replacement_map.rb
lib/setupmanagers/qemuhck/devices/ivshmem-doorbell.json
lib/setupmanagers/qemuhck/devices/tpm-tis.json
lib/setupmanagers/qemuhck/devices/vhost-user-fs-pci.json
lib/setupmanagers/qemuhck/network_manager.json
lib/setupmanagers/qemuhck/network_manager.rb
lib/setupmanagers/qemuhck/qemu_machine.rb
lib/setupmanagers/qemuhck/storage_manager.rb

QEMU binds smbd to lo so it needs to be up.

Misc changes related to SMB

---

lib/cli.rb

Part of https://github.com/HCK-CI/AutoHCK/pull/376

Unify methods to define command line options (based on Akihiko Odaki PR)

---

lib/engines/config_manager/config_manager.rb
lib/engines/engine.rb
lib/engines/hckinstall/hckinstall.rb
lib/engines/hcktest/hcktest.rb
lib/engines/hcktest/playlist.rb
lib/engines/hcktest/targets.rb
lib/engines/hcktest/tests.rb
lib/project.rb
lib/resultuploaders/dropbox/dropbox.rb
lib/setupmanagers/hckclient.rb
lib/setupmanagers/hckstudio.rb
lib/setupmanagers/setupmanager.rb

Part of https://github.com/HCK-CI/AutoHCK/pull/376

 Improve the workspace initialization mechanism (based on Akihiko Odaki PR)

---

lib/engines/hcktest/hcktest.rb
lib/setupmanagers/qemuhck/network_manager.rb

Part of https://github.com/HCK-CI/AutoHCK/pull/376

Do not check file existence before calling Json.read_json  (based on Akihiko Odaki PR)
