lib/github.rb, lib/project.rb
If provided invalid GitHub commit hash the test session will not start.
this commit will allow it to continue running without github status checks
=> Continue running if github commit hash not valid

config.json, lib/virthck.rb, platforms.json
This series adds additional configurations with the possibility to use default values on platforms configurations when not specified.
platform configurations:
* machine_type
* s3
* s4
* enlightenments_state
* vhost_state
general configurations:
* ivshmem_server_bin
* filesystem_tests_image
=> Additional platforms configurations

devices.json
This test fails but never returns which causes a stall to our testing
progress, putting it in the blacklist until the issue is fixed.
=> Adding 'Run RSC Tests' to 'Red Hat VirtIO Ethernet Adapter' blacklist

bin/auto_hck
Now single machine devices will run two clients and split tests between machines.
For client/support machine devices tests that require single machines will also be shared between both of the clients.
=> Utilize toolsHCK update to support concurrent tests running

lib/tests.rb
toolsHCK was updates to use strings instead of ids
=> Schedule options as strings

lib/tests.rb
reverting due to a change made to toolsHCK and wasn't working as expected.
This reverts commit 2ebdb8b6b07f061aaee6134766ac08595a49f85f.
=> Revert "Schedule options as strings"

lib/client.rb, lib/monitor.rb
Initializing a Monitor instance on shutdown_machine method call is not a good practice.
The idea behind this implementation is that sometimes the machines do shutdown and the Monitor instance would be invalid if initialized in the constructor of a Client instance.
This commit changes:
1. The behavior of a Monitor class without changing its functionality. (a telnet session is initialized on each action call then it is closed)
2. Moves the initialization of Monitor instance to the constructor of Client.
=> Proofing the Monitor instance of a Client

lib/virthck.rb
cmd variable is an array of strings, join is required before system
command call.
=> Fixing VirtHCK system command call

lib/tests.rb, lib/tools.rb
Failed test result logs archive will not fail the AutoHCK run anymore, and
will only skip the archiving and log a corresponding message to indicate
this behavior.
=> Archiving test result logs failure behavior update

lib/dropbox.rb, lib/result_uploader.rb, lib/tests.rb
This series of commits, allows autohck to check for old test logs and delete them in case of faliure,
this is useful in case tests pass with filter and when tests are rerun.
=> Old Test result removal

devices.json, lib/client.rb, lib/tools.rb
Some devices require some minor configurations pre testing, added
an optional 'pretestcommands' field to devices in devices.json, and
added the code to run them in order, if they exist.
=> Pre test commands based on device

bin/auto_hck, lib/github.rb, lib/project.rb
1. Fixed where no matter what was the outcome of HCK-CI run, PR
status will be updated to error in the end.
2. Added a cancel HCK-CI run scenario with its corresponding PR
status update.
=> Github PR status update fixes

config.json, lib/auxiliary/host_helper.rb, lib/auxiliary/iso_helper.rb, lib/cli.rb, lib/engines/engine.rb, lib/engines/hckinstall/hckinstall.json, lib/engines/hckinstall/hckinstall.rb, lib/engines/hckinstall/iso.json, lib/engines/hckinstall/setup_scripts_helper.rb, lib/engines/hcktest/hcktest.rb, lib/project.rb, lib/setupmanagers/machine.rb, lib/setupmanagers/physhck/physhck.rb, lib/setupmanagers/setupmanager.rb, lib/setupmanagers/virthck/virthck.rb
The current implementation has a few limitations, that will be fixed in the next PR
- ~~install engine installs all images (studio and 2 clients), existing studio image will be used unless - **--force option is added**~~
- studio and client VMs will be installed from the one Windows ISO - **client platform will be parsed from filename**
- the corresponding version of HCK/HLK should be downloaded manually - **automatic download will be implemented**
- the corresponding windows ISO should be downloaded manually - **automatic download will be implemented**
=> Initial implementation of image creation

lib/project.rb
This is needed to prevent status adding for drivers that
will be not tested.
Fix wrong status at https://github.com/virtio-win/kvm-guest-drivers-windows/pull/563
=> project: Configure GitHub status after diff_checker

lib/engines/hckinstall/kit.json
HLK Studio for Windows Server 2019 and Windows 10 1809 contain
a bug with the PNP Surprise removal test. MS provided an updated
binary that should solve the failure.
=> kit.json: Install fix for HLK1809

.gitignore
AutoHCK-Installer can create `/override.old` and `/override.install.json`.
Signed-off-by: Akihiko Odaki <akihiko.odaki@daynix.com>
=> Add /override.* to .gitignore

lib/setupmanagers/qemuhck/network_manager.rb, lib/setupmanagers/qemuhck/qemu_machine.rb
Before this change, `QemuMachine` used to run the command to delete the network control bridge for each client. The later command executions was failing because the bridge was already removed with the earlier command and it did no longer exist.
With this change, the studio machine solely manages the network control bridge, and clients do no longer try to delete the network control bridge by its own. In fact, such a behavior was already present for the other network devices, and this change merely expands the scope of the behavior.
=> QemuHCK: Let studio manage network control bridge

lib/setupmanagers/qemuhck/network_manager.rb
bridge netfilter sysctls do not exist if `br_netfilter` is not loaded. As the sysctls are only used to disable bridge netfilter, it is safe to ignore the sysctls if they do not exist.
=> Ignore bridge netfilter sysctls if not exist

.circleci/config.yml, .github/workflows/rubocop.yml, Gemfile, Gemfile.lock, bin/ns, bin/ns_unshared, config.json, lib/setupmanagers/hckstudio.rb, lib/setupmanagers/physhck/physhck.rb, lib/setupmanagers/qemuhck/network_manager.rb, lib/setupmanagers/qemuhck/qemu_machine.json, lib/setupmanagers/qemuhck/qemu_machine.rb, lib/setupmanagers/qemuhck/qemuhck.rb, lib/setupmanagers/qemuhck/slirp.rb, lib/version.rb, resolv.conf
Although I said the command invocation will be `bin/ns bin/auto_hck` in an internal meeting, ~~I decided to make it work just by `bin/auto_hck`~~. `bin/ns` still exists for manual testing.
Don't forget to install slirp4netns before testing.
=> Create own network namespace

.github/workflows/codeql-analysis.yml
CodeQL Action v1 will be deprecated on December 7th, 2022.
=> CI: Bump CodeQL Action version

lib/engines/hcktest/hcktest.rb, lib/engines/hcktest/targets.rb, lib/engines/hcktest/tests.rb
=> Fix RuboCop LineContinuationSpacing offense

lib/engines/hcktest/tests.rb, lib/version.rb
This is a workaround for production to prevent crashes and
ability to collect more logs for debugging.
=> Add missing test extra

bin/ns
=> Enable setgroups

bin/ns_unshared
If bin/ns is executed by root, mounts can be propagated to the root namespace. Prevent that by recursively converting / to private mount.
=> Recursively convert / to private mount

drivers.json
It is confirmed that the tests are passing with the following QEMU version:
https://github.com/daynix/qemu/commit/5af17491d0326b8aa8fea93a81c35903ca0bf60c
It is probable that the tests are fine but the inaccuracy of QEMU's packet counters, which was fixed recently, affected them. Remove them from the ignore list.
=> Remove some tests from the ignore list of igb

lib/engines/hcktest/platforms/Win11_22H2x64_host_uefi_q35_viommu.json, lib/engines/hcktest/platforms/Win11nextx64_host_uefi_q35_viommu.json, lib/engines/hcktest/platforms/Win2019x64.json, lib/engines/hcktest/platforms/Win2019x64_uefi.json, lib/engines/hcktest/platforms/Win2022nextx64_host_uefi_q35_viommu.json, lib/engines/hcktest/platforms/Win2022x64.json, lib/engines/hcktest/platforms/Win2022x64_host_uefi_q35_viommu.json, lib/engines/hcktest/platforms/Win2022x64_uefi.json
Microsoft recommends at least 1GB of RAM for 1 CPU. Several tests require more resources, so set 2GB of RAM for 1 CPU.
After a talk with Yuri, he recommends increasing RAM. We have enough resources for this on CI servers.
=> Increase RAM memory for several platforms

bin/auto_hck, lib/auxiliary/cmd_run.rb, lib/auxiliary/id_gen.rb, lib/auxiliary/resource_scope.rb, lib/engines/config_manager/config_manager.rb, lib/engines/hckinstall/hckinstall.rb, lib/engines/hckinstall/setup_scripts_helper.rb, lib/engines/hcktest/hcktest.rb, lib/engines/hcktest/tests.rb, lib/exceptions.rb, lib/project.rb, lib/resultuploaders/result_uploader.rb, lib/setupmanagers/hckclient.rb, lib/setupmanagers/hckstudio.rb, lib/setupmanagers/physhck/physhck.rb, lib/setupmanagers/qemuhck/qemu_machine.rb, lib/setupmanagers/qemuhck/qemuhck.rb, lib/setupmanagers/qemuhck/qmp.rb, lib/setupmanagers/setupmanager.rb, lib/trap.rb
I have already done several changes to improve the abortion logic, but I still see an error occurs during abortion. I also heard AutoHCK sometimes hangs after the tests finish, which imply some resources associated threads are left unreleased.
To eliminate this kind of errors completely, I propose `AutoHCK::ResourceScope` as a single true resource management mechanism.
This pull request makes *every* code dealing with unmanaged resources use the new mechanism so it's huge. Take time if it's correctly used everywhere before merging.
=> Introduce AutoHCK::ResourceScope

lib/setupmanagers/qemuhck/qemu_machine.rb
When QEMU exits, device daemons exit too, so we should run it again before start QEMU.
=> Run pre start command before each QEMU run

lib/engines/hckinstall/kit.json, lib/engines/hckinstall/studio_platform.json, lib/engines/hcktest/platforms/Win2022nextx64_host_uefi_q35_viommu.json
Windows Server vNext Build 25941 required other HLK and playlist.
=> Define new HLK2022_next kit

lib/auxiliary/cmd_run.rb
When multiple commands start in parallel it is difficult to understand what exactly fails.
=> Add PID to each CmdRun log

lib/version.rb
There are a lot of changes in JSONs (refactoring/moving), that can break backward compatibility. Bump minor version.
=> Bump AutoHCK version (0.13.0)

lib/auxiliary/time_helper.rb, lib/engines/hcktest/tests.rb, lib/project.rb
=> AutoHCK fail when rerun test with BSOD

lib/engines/hcktest/drivers/viomem.json, lib/models/driver.rb, lib/setupmanagers/qemuhck/devices/virtio-mem-pci.json, lib/setupmanagers/qemuhck/qemu_machine.rb, lib/setupmanagers/qemuhck/qemuhck.rb
@YanVugenfirer Please wait for merge untill get answer https://github.com/virtio-win/kvm-guest-drivers-windows/pull/794#issuecomment-1192287484
=> Add VirtIO Viomem Driver support

lib/setupmanagers/qemuhck/network_manager.rb
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: tap_host: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br_world state UNKNOWN mode DEFAULT group default qlen 1000
link/ether aa:c5:7d:6d:c6:a2 brd ff:ff:ff:ff:ff:ff
3: br_world: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 11000
link/ether 2e:69:fe:af:28:ad brd ff:ff:ff:ff:ff:ff
4: br_ctrl: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 11000
link/ether 4a:7b:69:83:c0:ed brd ff:ff:ff:ff:ff:ff
5: br_test: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 11000
link/ether …
=> Give meaningful names to test tap devices

lib/engines/hcktest/drivers/vioscsi.json, lib/engines/hcktest/drivers/viostor.json
Initialize-Disk for some reason creates a small partition, so we must remove it before creating a new one. This behavior was tested on Server 2016/2022/2025.
=> Initialize partition for viostor/vioblk testing

lib/engines/hcktest/tests.rb, lib/setupmanagers/qemuhck/qemu_machine.rb, lib/setupmanagers/qemuhck/qemuhck.rb
https://issues.redhat.com/browse/RHELMISC-4835
current host.txt looks like: 
here is logs.txt output
=> Add useful info to log

lib/version.rb
Backward compatibility is broken, so bump a minor version.
=> Bump AutoHCK version (0.15.0)

lib/setupmanagers/hckstudio.rb
HCKStudio keeps the reference to the Tools instance it creates so the referenced instance needs to be alive until HCKStudio dies. However, HCKStudio used to register a Tools instance to the ResourceScope when the instance gets created, which is later than the HCKStudio initialization. This implies the Tools instance gets closed earlier than HCKStudio, and HCKStudio will keep the dangling reference to the Tools instance.
This caused an exception in case
HCKTest::configure_setup_and_synchronize got interrupted. Such an interrupt first triggers the Tools instance closure earlier than the closure of the HCKStudio and HCKClient instances, and made HCKClient instances, which tries to use the Tools instance, fail.
Closing the Tools instance when HCKStudio dies extends its lifetime properly.
=> Correct Tools closure timing

bin/ns_unshared
We use unshare command, which performs the identical operation since commit 86274a8518cebf8d4dc91aedd7079bd0ae75e9e6.
=> Remove mount --make-rprivate / execution

lib/all.rb, lib/auxiliary/github.rb, lib/exceptions.rb, lib/project.rb
Sometimes we got `Failed to open TCP connection to [api.github.com:443](http://api.github.com:443/) (getaddrinfo: Name or service not known)`  during CI run. 
If it happens at the start we should fail, because we can't get information about PR and don't know should we run tests or not.
If it happens during check_run_termination we can skip this iteration and AutoHCK will check again later. As CI time is several hours or even a day, this is not a problem to terminate CI not in one minute but in five.
=> Continue run when can't load PR update 

lib/resultuploaders/dropbox/dropbox.rb
Currently, Dropbox API can raise OAuth2::ConnectionError when failed to resolve DNS name.
=> Dropbox: Handle OAuth2::ConnectionError as Faraday::ConnectionFailed

lib/resultuploaders/dropbox/dropbox.rb
`I, [2025-03-03T05:52:13.414770 #333237]  INFO -- : Navigate to https://www.dropbox.com/oauth2/authorize?client_id=vah03z3dsrd4f3w&response_type=code&token_access_type=offline
I, [2025-03-03T05:52:13.414861 #333237]  INFO -- : Please enter authorization code
F, [2025-03-03T05:52:13.415000 #333237] FATAL -- : (Errno::ENOENT) No such file or directory @ rb_sysopen - config
-- /home/jedoku/HCK/repos/AutoHCK.git/lib/resultuploaders/dropbox/dropbox.rb:72:in `gets'
-- /home/jedoku/HCK/repos/AutoHCK.git/lib/resultuploaders/dropbox/dropbox.rb:72:in `gets'
-- /home/jedoku/HCK/repos/AutoHCK.git/lib/resultuploaders/dropbox/dropbox.rb:72:in `ask_token'
-- /home/jedoku/HCK/repos/AutoHCK.git/lib/resultuploaders/result_uploader.rb:49:in `each_value'
-- …
=> Fix dropbox enter authorization code

lib/engines/hcktest/tests.rb
Fix 54a1c0a2b968f4427035940e563f24098d99eb04.
Regexp.union has escape symbols in string for some undocumented reason.
3.3.7 :001 > x = Regexp.new("asd|.*")
=> /asd|.*/
3.3.7 :002 > y = Regexp.union(["asd", ".*"])
=> /asd|\.\*/
3.3.7 :003 >
3.3.7 :002 > x = Regexp.new(".*")
=> /.*/
3.3.7 :003 > y = Regexp.new("sdsd")
=> /sdsd/
3.3.7 :004 > z = Regexp.union(x, y)
=> /(?-mix:.*)|(?-mix:sdsd)/
=> RHELMISC-10178: test: Match test names as regexp

lib/setupmanagers/qemuhck/machine.json, lib/setupmanagers/qemuhck/network_manager.json
This allows to use NetKVM as a control network device with IOMMU enabled.
virtio-pci swithes to legacy mode, when device attached to pcie bus instead of root port.
This brake backward compatibility as a PCI topology changes and Windows reconfigure devices.
=> RHELMISC-11270: QemuHCK: Attach control network device to pcie-root-port

lib/project.rb, lib/resultuploaders/fs_copy/fs_copy.json, lib/resultuploaders/fs_copy/fs_copy.rb, lib/resultuploaders/result_uploader.rb
Can be used to mount NFS storage and upload logs to it.
~~This PR is a draft due to an issue with AutoHCK.log uploading.
As a result uploaders are created after the Project, we close them before closing the project. 
It caused the problem, that AutoHCK.log must be uploaded after result uploaders were closed.
We did not see any errors before, because `def close` is empty in Dropbox/S3 uploaders but even logically this is a problem.~~
```
I, [2025-03-27T20:45:58.530397 #58880]  INFO -- CmdRun PID:73517: Command finished with code 0
I, [2025-03-27T20:45:58.541493 #58880]  INFO -- CmdRun PID:73521: Run command: gio mount 'smb://WORKGROUP;iadmin@10.7.2.11/kostyanf14' --unmount
I, [2025-03-27T20:45:58.557758 #58880]  INFO -- CmdRun PID:73521: stderr: 
I, [2025-03-27T20:45:58.558214 #58880] …
```
=> RHELMISC-10658: Implement log upload to external FS

lib/engines/hckinstall/kits/HLK11_22H2.json, lib/engines/hckinstall/kits/HLK11_23H2.json, lib/engines/hckinstall/kits/HLK11_24H2.json, lib/engines/hckinstall/kits/HLK1809.json, lib/engines/hckinstall/kits/HLK1809server.json, lib/engines/hckinstall/kits/HLK2004.json, lib/engines/hckinstall/kits/HLK2022.json, lib/engines/hckinstall/kits/HLK2025.json
HLK for Win11 23H2 was removed.
=> RHELMISC-12099: Update HLK kit urls

lib/resultuploaders/dropbox/dropbox.rb
share_folder - Share a folder with collaborators
(other Dropbox accounts).
This endpoint does not support apps with the app folder permission.
create_shared_link_with_settings - Create a shared link with custom settings. If no settings are given then the default visibility is RequestedVisibility.public (The resolved visibility, though, may depend on other aspects such as team and shared folder settings).
=> Dropbox: Remove share_folder call

lib/engines/hcktest/drivers/vioscsi.json, lib/engines/hcktest/drivers/viostor.json
In some case, HLK test can finishes after removing partition. In this case, AutoHCK should not fail run and just create a new partition.
=> viostor/vioscsi: Ignore remove partition fail
